### ISSUE TITLE
Unable to load saved models to use on other datasets

### ISSUE THREAD

**Issue by nfaux** [google/NeuroNER-CSPMC#2]
Hi,

I am trying to test these models on a set of documents, but keep hitting the same error.

Using the following call:

```bash
python util.py --eval --pretrained_model_folder=/Users/nfaux/Documents/Projects/Repos/NeuroNER-CSPMC/neuroner/trained_models/conll_2003_en/ --dataset_text_folder=/Users/nfaux/Documents/Projects/Vespoor_Boyle_deid/TestData --rbias=0 --edim=300
```

The following error was :

```log
INFO:tensorflow:Restoring parameters from /Users/nfaux/Documents/Projects/Repos/NeuroNER-CSPMC/neuroner/trained_models/conll_2003_en/model.ckpt
I0825 13:45:48.613111 4643708352 saver.py:1284] Restoring parameters from /Users/nfaux/Documents/Projects/Repos/NeuroNER-CSPMC/neuroner/trained_models/conll_2003_en/model.ckpt
done (251.81 seconds)
Checkpoint file is: /Users/nfaux/Documents/Projects/Repos/NeuroNER-CSPMC/neuroner/trained_models/conll_2003_en/model.ckpt
Traceback (most recent call last):
  File "/Users/nfaux/opt/anaconda3/envs/neuroNER-CSPM/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/Users/nfaux/opt/anaconda3/envs/neuroNER-CSPM/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/Users/nfaux/opt/anaconda3/envs/neuroNER-CSPM/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1,300] rhs shape= [1,100]
	 [[{{node save/Assign_17}}]]
```

I have tried the following models, `conll_2003_en model`, `i2b2_2014_glove_stanford_bioes` and `i2b2_2014_glove_spacy_bioes`.

The setup is on a 16inch MBPro. Note I had to change the tensorflow version from 1.1.0, 1.1.15.
Figured out the parameter.ini file needs to be in the same dir that you call the util.py from. 

In the `../neuro/data/word_vectors` dir I have the `glove.6B.100d.txt` and `glove.840B.300d.txt` files.

In the `dataset_text_folder` I have the deploy folder containing the desired text which to run the models over.

Note: It would be good to update the `readme`, to make it explicit where the parameter.ini file needs to be, as well as the exact directory structure the new data/test data needs to be in.

**Comment by amitmarkel** [comment]
Hi,

The entire directory `NeuroNER-CSPMC/neuroner/trained_models` is out of date as it contains the original models prior to the main forked branch: dates back to before our `Modifications` commit.

The checkpoints are not compatible because we added variables. Also, if I recall correctly, we added features to `dataset.pickle`, hence it is out of date as well.

Unfortunately, we don't have our models any more, so they will have to be reconstructed.

I'll delete the directory and/or prepend a notice in README to prevent confusion.
Sorry for the late reply and out of date models.

**Comment by nfaux** [comment]
Hi Amit,

Thanks for the update and the explanation. Are there plans to reconstruct the models used in the paper and update the repo? 

Many thanks
